from enum import IntEnum

class Keypoints(IntEnum):
  NOSE = 0
  LEFT_SHOULDER = 11
  LEFT_WRIST = 15
  RIGHT_WRIST = 16
  LEFT_HIP = 23
  RIGHT_HIP = 24
  LEFT_KNEE = 25
  RIGHT_KNEE = 26
  LEFT_ANKLE = 27
  RIGHT_ANKLE = 28
  RIGHT_SHOULDER = 12
  LEFT_FOOT_INDEX = 31
  RIGHT_FOOT_INDEX = 32
